// Module included in the following assemblies:
//
// * network_observability/observing-network-traffic.adoc

:_mod-docs-content-type: PROCEDURE
[id="network-observability-packet-translation_{context}"]
= Working with endpoint translation (xlat)

[role="_abstract"]
Enable endpoint translation (xlat) in the `FlowCollector` resource to enrich network flows with translated packet information. You can use this information to identify the specific pods and objects serving service traffic through dedicated xlat columns.

You can use network observability and eBPF to enrich network flows from a Kubernetes service with translated endpoint information, gaining insight into the endpoints serving traffic.

.Procedure
. In the web console, navigate to *Ecosystem* -> *Installed Operators*.
. In the *Provided APIs* heading for the *NetObserv Operator*, select *Flow Collector*.
. Select *cluster*, and then select the *YAML* tab.
. Configure the `FlowCollector` custom resource for `PacketTranslation`, for example:
+
[source, yaml]
----
apiVersion: flows.netobserv.io/v1beta2
kind: FlowCollector
metadata:
  name: cluster
spec:
  namespace: netobserv
  agent:
    type: eBPF
    ebpf:
      features:
       - PacketTranslation
----
+
where:

`spec.agent.ebpf.features.PacketTranslation`:: Specifies enriching network flows with translated packet information.

. Click *Save*.

.Verification
. Refresh the *Network Traffic* page.
. In the *Traffic flows* view, filter the data by selecting *Service* from the *Destination kind* drop-down menu.
. Verify that the following columns are visible in the table:
* *Xlat Zone ID*
* *Xlat Src Kubernetes Object*
* *Xlat Dst Kubernetes Object*
. Optional: To display more fields, click *Manage columns* and select the required *xlat* columns.
