// Module included in the following assemblies:
//
// network_observability/observing-network-traffic.adoc

:_mod-docs-content-type: PROCEDURE
[id="network-observability-filtering-ebpf-rule_{context}"]
= Filtering eBPF flow data using multiple rules
You can configure the `FlowCollector` to filter eBPF flows using multiple rules to control the flow of packets cached in the eBPF flow table.

[IMPORTANT]
====
* You cannot use duplicate CIDRs in filter rules.
* If an IP matches several rules, only the rule with the longest CIDR prefix is evaluated.
====

.Procedure
. In the web console, navigate to *Operators* -> *Installed Operators*.
. Under the *Provided APIs* heading for *Network Observability*, select *Flow Collector*.
. Select *cluster*, then select the *YAML* tab.
. Configure the `FlowCollector` custom resource, similar to the following sample configurations:
+

.Example YAML to sample all North-South traffic, and 1:50 East-West traffic
====
[source, yaml]
----
apiVersion: flows.netobserv.io/v1beta2
kind: FlowCollector
metadata:
  name: cluster
spec:
  namespace: netobserv
  deploymentModel: Direct
  agent:
    type: eBPF
    ebpf:
      flowFilter:
        enable: true <1>
        rules:
         - action: Accept <2>
           cidr: 0.0.0.0/0 <3>
           sampling: 1 <4>
         - action: Accept
           cidr: 10.128.0.0/14
           peerCIDR: 10.128.0.0/14 <5>
         - action: Accept
           cidr: 172.30.0.0/16
           peerCIDR: 10.128.0.0/14
           sampling: 50
----
<1> You must set `spec.agent.ebpf.flowFilter.enable` to `true` to enable eBPF flow filtering.
<2> The required `action` parameter describes the action that is taken for the flow filter rule. Possible values are `Accept` or `Reject`.
<3> The required `cidr` parameter provides the IP address and CIDR mask for the flow filter rule and supports IPv4 and IPv6 address formats. If you want to match against any IP address, you can use `0.0.0.0/0` for IPv4 or `::/0` for IPv6.
<4> Sampling rate for the matched flows, overriding the global sampling defined at `spec.agent.ebpf.sampling`.
<5> The Peer IP CIDR to filter flows by.
+
By default, all other flows are rejected.
====
+
.Example YAML to filter flows with packet drops
====
[source, yaml]
----
apiVersion: flows.netobserv.io/v1beta2
kind: FlowCollector
metadata:
  name: cluster
spec:
  namespace: netobserv
  deploymentModel: Direct
  agent:
    type: eBPF
    ebpf:
      privileged: true <1>
      features:
        - PacketDrop <2>
      flowFilter:
        enable: true <3>
        rules:
          - action: Accept <4>
            cidr: 172.30.0.0/16
            pktDrops: true <5>
----
<1> You must set `spec.agent.ebpf.privileged` to `true` for the packet drop feature.
<2> You can start reporting the packet drops of each network flow by listing the `PacketDrop` parameter in the `spec.agent.ebpf.features` specification list.
<3> You must set `spec.agent.ebpf.flowFilter.enable` to `true` to enable eBPF flow filtering.
<4> The required `action` parameter describes the action that is taken for the flow filter rule. Possible values are `Accept` or `Reject`.
<5> Set `pktDrops` to `true` to filter flows containing drops.

By default, all other flows are rejected.
====
//05/01/2025: %collapsible is not supported in PV1, and may not be supported in AEM, so removed. This comment can be deleted when OSDOCS-14479 is closed.