// Module included in the following assemblies:
//
// network_observability/observing-network-traffic.adoc

:_mod-docs-content-type: PROCEDURE
[id="network-observability-filtering-ebpf-rule_{context}"]
= Filtering eBPF flow data
You can configure the `FlowCollector` to filter eBPF flows using multiple rules and features to control the flow of packets cached in the eBPF flow table.

.Procedure
. In the web console, navigate to *Operators* -> *Installed Operators*.
. Under the *Provided APIs* heading for *Network Observability*, select *Flow Collector*.
. Select *cluster*, then select the *YAML* tab.
. Configure the `FlowCollector` custom resource, similar to the following sample configuration:
+
.Example `FlowCollector` YAML with multiple rules
+
[source, yaml]
----
apiVersion: flows.netobserv.io/v1beta2
kind: FlowCollector
metadata:
  name: cluster
spec:
  namespace: netobserv
  deploymentModel: Direct
  agent:
    type: eBPF
    ebpf:
      privileged: true <1>
      features: <2>
        - PacketDrop
        - FlowRTT
      flowFilter:
        enable: true <3>
        rules:
          - action: Accept  <4>
            cidr: 172.210.150.1/24 <5>
            protocol: SCTP
            direction: Ingress
            destPortRange: 80-100
            peerIP: 10.10.10.10
          - action: Accept
            cidr: 172.30.0.0/16
            pktDrops: true <6>
          - action: Reject
            cidr: 0.0.0.0/0
----
+
<1> The `spec.agent.ebpf.privileged` specification value must be true for packet drop tracking.
<2> List the parameters you want to track in the `spec.agent.ebpf.features` specification list.
<3> You must set `spec.agent.ebpf.flowFilter.enable` to `true` to enable this feature.
<4> The required `action` parameter describes the action that is taken for the flow filter rule. Possible values are `Accept` or `Reject`.
<5> The required `cidr` parameter provides the IP address and CIDR mask for the flow filter rule and supports IPv4 and IPv6 address formats. If you want to match against any IP address, you can use `0.0.0.0/0` for IPv4 or `::/0` for IPv6. Duplicate CIDRs are not allowed in filter rules.
<6> The `PacketDrop` feature requires an `action` parameter.