// Module included in the following assemblies:
//
// network_observability/observing-network-traffic.adoc

:_mod-docs-content-type: PROCEDURE
[id="network-observability-filtering-ebpf-rule_{context}"]
= Filtering eBPF flow data using multiple rules
You can configure the `FlowCollector` to filter eBPF flows using multiple rules to control the flow of packets cached in the eBPF flow table.

.Procedure
. In the web console, navigate to *Operators* -> *Installed Operators*.
. Under the *Provided APIs* heading for *Network Observability*, select *Flow Collector*.
. Select *cluster*, then select the *YAML* tab.
. Configure the `FlowCollector` custom resource, similar to the following sample configuration:

[IMPORTANT]
====
You cannot use duplicate CIDRs in filter rules
====
+

[%collapsible]
.Filter Kubernetes service traffic to a specific Pod IP endpoint and service flows with Drops
====
[source, yaml]
----
apiVersion: flows.netobserv.io/v1beta2
kind: FlowCollector
metadata:
  name: cluster
spec:
  namespace: netobserv
  deploymentModel: Direct
  agent:
    type: eBPF
    ebpf:
      privileged: true <1>
      features:
        - PacketDrop
      flowFilter:
        enable: true <2>
        rules:
          - action: Accept  <3>
            cidr: 172.210.150.1/24 <4>
            protocol: SCTP
            direction: Ingress
            destPortRange: 80-100
            peerIP: 10.10.10.10
          - action: Accept
            cidr: 172.30.0.0/16
            pktDrops: true <5>
----
<1> You must set `spec.agent.ebpf.privileged` to `true` for the packet drop feature.
<2> You must set `spec.agent.ebpf.flowFilter.enable` to `true` to enable eBPF flow filtering.
<3> The required `action` parameter describes the action that is taken for the flow filter rule. Possible values are `Accept` or `Reject`.
<4> The required `cidr` parameter provides the IP address and CIDR mask for the flow filter rule and supports IPv4 and IPv6 address formats. If you want to match against any IP address, you can use `0.0.0.0/0` for IPv4 or `::/0` for IPv6.
<5> By default, all other flows are rejected.
====
+
[%collapsible]
.See flows to any addresses outside the cluster
====
[source, yaml]
----
apiVersion: flows.netobserv.io/v1beta2
kind: FlowCollector
metadata:
  name: cluster
spec:
  namespace: netobserv
  deploymentModel: Direct
  agent:
    type: eBPF
    ebpf:
      flowFilter:
        enable: true <1>
        rules:
        - action: Accept  <2>
          cidr: 0.0.0.0/0 <3>
          protocol: TCP
          direction: Egress
          sourcePort: 100
          peerIP: 192.168.127.12 <4>
----
<1> You must set `spec.agent.ebpf.flowFilter.enable` to `true` to enable eBPF flow filtering.
<2> The required `action` parameter describes the action that is taken for the flow filter rule. Possible values are `Accept` or `Reject`.
<3> The `cidr` value of `0.0.0.0/0` matches against any IP address.
<4> See flows after `peerIP` is configured with `192.168.127.12`. By default, all other flows are rejected.
====