// Module included in the following assemblies:
//
// network_observability/observing-network-traffic.adoc

:_mod-docs-content-type: PROCEDURE
[id="network-observability-filtering-ebpf-rule_{context}"]
= Filtering eBPF flow data using multiple rules
You can configure the `FlowCollector` to filter eBPF flows using multiple rules to control the flow of packets cached in the eBPF flow table.

.Procedure
. In the web console, navigate to *Operators* -> *Installed Operators*.
. Under the *Provided APIs* heading for *Network Observability*, select *Flow Collector*.
. Select *cluster*, then select the *YAML* tab.
. Configure the `FlowCollector` custom resource, similar to the following sample configuration:

[IMPORTANT]
====
You cannot use duplicate CIDRs in filter rules.
====

.Example YAML for EastWest and NorthSouth traffic
+
[source, yaml]
----
apiVersion: flows.netobserv.io/v1beta2
kind: FlowCollector
metadata:
  name: cluster
spec:
  namespace: netobserv
  deploymentModel: Direct
  agent:
  type: eBPF
  ebpf:
    flowFilter:
      enable: true <1>
      rules:
        - action: Accept <2>
          cidr: 172.30.0.0/16 <3>
          peerCIDR: 10.128.0.0/14
          sampling: 10
        - action: Accept
          cidr: 10.128.0.0/14
          peerCIDR: 10.128.0.0/14
          sampling: 20
        - action: Accept
          cidr: 8.8.8.8/32
          sampling: 30
          peerCIDR: 10.128.0.0/14
          protocol: ICMP
          icmpType: 8
----
<1> You must set `spec.agent.ebpf.flowFilter.enable` to `true` to enable eBPF flow filtering.
<2> The required `action` parameter describes the action that is taken for the flow filter rule. Possible values are `Accept` or `Reject`.
<3> The required `cidr` parameter provides the IP address and CIDR mask for the flow filter rule and supports IPv4 and IPv6 address formats. If you want to match against any IP address, you can use `0.0.0.0/0` for IPv4 or `::/0` for IPv6. By default, all other flows are rejected.

.Example YAML for packet drops
+
[source, yaml]
----
apiVersion: flows.netobserv.io/v1beta2
kind: FlowCollector
metadata:
  name: cluster
spec:
  namespace: netobserv
  deploymentModel: Direct
  agent:
    type: eBPF
    ebpf:
      privileged: true <1>
    features:
      - PacketDrop
    flowFilter:
      enable: true <2>
      rules:
        - action: Accept <3>
          cidr: 172.30.0.0/16
          pktDrops: true <4>
        - action: Reject
          cidr: 0.0.0.0/0
----
<1> You must set `spec.agent.ebpf.privileged` to `true` for the packet drop feature.
<2> You must set `spec.agent.ebpf.flowFilter.enable` to `true` to enable eBPF flow filtering.
<3> The required `action` parameter describes the action that is taken for the flow filter rule. Possible values are `Accept` or `Reject`.
<4> By default, all other flows are rejected.

//05/01/2025: %collapsible is not supported in PV1, and may not be supported in AEM, so removed. This comment can be deleted when OSDOCS-14479 is closed.