// Module included in the following assemblies:
//
// * service-mesh-docs-main/metrics/ossm-metrics.adoc

:_mod-docs-content-type: PROCEDURE
[id="ossm-config-openshift-monitoring-ambient-mode_{context}"]
= Configuring OpenShift Monitoring with Service Mesh ambient mode

[role="_abstract"]

You can integrate {SMProductName} with user-workload monitoring to enable observability in your service mesh ambient mode. User-workload monitoring provides access to essential built-in tools. Kiali requires this feature to run the dedicated console for {istio}.

.Prerequisites

* You have installed the {SMProductName} Operator.

* You have enabled the user-workload monitoring.
+
[NOTE]
====
You can enable user workload monitoring by applying the `ConfigMap` change for metrics integration. For more information, see "Configuring user workload monitoring".
====

.Procedure

. Create a `Service` resource to define a port that uses the metrics exposed by the ztunnel, similar to the following example:

+
[source,yaml]
----
apiVersion: v1
kind: Service
metadata:
  name: ztunnel
  namespace: ztunnel
  labels:
    app: ztunnel
    service: ztunnel
spec:
  selector:
    app: ztunnel
  ports:
    - name: http-monitoring
      protocol: TCP
      port: 15020
      targetPort: 15020
----

. Create a `ServiceMonitor` resource that monitors the {istio} control plane, similar to the following example:
+
[source,yaml]
----
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istiod-monitor
  namespace: istio-system
spec:
  targetLabels:
  - app
  selector:
    matchLabels:
      istio: pilot
  endpoints:
  - port: http-monitoring
    interval: 30s
----

. Create a `ServiceMonitor` resource that collects the ztunnel metrics, similar to the following example:
+
[source,yaml]
----
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ztunnel-monitor
  namespace: ztunnel
spec:
  targetLabels:
  - app
  selector:
    matchLabels:
      service: ztunnel
  endpoints:
  - port: http-monitoring
    interval: 30s
----
+
where:

`mesh_id`:: Specify the actual mesh ID.
`\\d+`:: The additional backslash is only used when you apply this replacement from a command line through heredoc. If you apply this from a YAML file, replace `\\d+` with `\d+`.
`\$`:: The backslash is only used when you apply this replacement from a command line through heredoc. If you apply this from a YAML file, replace `\$` with `$`.

. Optional: Deploy a waypoint proxy to enable the Layer 7 (L7) {SMProduct} features in ambient mode:

.. Deploy a custom waypoint proxy with additional labels and ports for the `bookinfo` namespace, similar to the following example:
+
[source,yaml]
----
 apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  labels:
    istio.io/waypoint-for: service
    app: waypoint
    service: waypoint
  name: waypoint
  namespace: bookinfo
spec:
  gatewayClassName: istio-waypoint
  listeners:
  - name: mesh
    port: 15008
    protocol: HBONE
  - name: http-monitoring
    protocol: TCP
    port: 15020
----
`<http-monitoring>`:: Specifies an additional port that exposes the metrics used by the waypoint proxy.

.. Enroll the namespace to use the waypoint by running the following command:
+
[source,terminal]
----
$ oc label namespace bookinfo istio.io/use-waypoint=waypoint
----

.. Create a `ServiceMonitor` resource that collects the waypoint proxy metrics for the `bookinfo` namespace, similar to the following example:
+
[source,yaml]
----
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: waypoint-monitor
  namespace: bookinfo
spec:
  targetLabels:
  - app
  selector:
    matchLabels:
      service: waypoint
  endpoints:
  - port: http-monitoring
    interval: 30s
----
+
where:

`mesh_id`:: Specify the actual mesh ID.
`\\d+`:: The additional backslash is only used when you apply this replacement from a command line through heredoc. If you apply this from a YAML file, replace `\\d+` with `\d+`.
`\$`:: The backslash is only used when you apply this replacement from a command line through heredoc. If you apply this from a YAML file, replace `\$` with `$`.

+
[NOTE]
====
A waypoint proxy generates Layer 4 (L4) and L7 metrics. It scopes these statistics by Envoy proxy functions. The Envoy proxy documentation describes the statistic functions, for example, `Upstream connection`, `Listener`, `HTTP Connection Manager`, `TCP proxy`, and `Router`.
====
