// Module included in the following assemblies:

// * power_monitoring/power-monitoring-configuration.adoc

:_mod-docs-content-type: CONCEPT
[id="power-monitoring-monitoring-kepler-status_{context}"]
= {PM-kepler} resource status

[role="_abstract"]
The `PowerMonitor` resource status field provides real-time information about Kepler pod deployment state and health across nodes.

The `status` field includes information, such as the following:

* The number of nodes currently running the {PM-kepler} pods
* The number of nodes that should be running the {PM-kepler} pods
* Conditions representing the health of the {PM-kepler} resource

This provides you with valuable insights into the changes made through the `spec` field.

.Example state of the `PowerMonitor` resource
[source,yaml]
----
apiVersion: kepler.system.sustainable.computing.io/v1alpha1
kind: PowerMonitor
metadata:
  name: power-monitor
status:
   conditions:
     - lastTransitionTime: '2024-01-11T11:07:39Z'
       message: Reconcile succeeded
       observedGeneration: 1
       reason: ReconcileSuccess
       status: 'True'
       type: Reconciled
     - lastTransitionTime: '2024-01-11T11:07:39Z'
       message: >-
         power-monitor daemonset "openshift-power-monitoring/power-monitor" is deployed to all nodes and
         available; ready 2/2
       observedGeneration: 1
       reason: DaemonSetReady
       status: 'True'
       type: Available
   currentNumberScheduled: 2
   desiredNumberScheduled: 2
----
+
where:

`status.conditions`:: Specifies the health of the `PowerMonitor` resource. In this example, the `PowerMonitor` resource is successfully reconciled and ready.
`status.currentNumberScheduled`:: Specifies the number of nodes currently running the {PM-kepler} pods.
`status.desiredNumberScheduled`:: Specifies the target number of nodes to run the {PM-kepler} pods.